export type InventoryStatus = "current" | "network" | "pick";

export const inventoryStatusContent: Record<
  InventoryStatus,
  {
    label: string;
    badge: string;
    disclosure: string;
  }
> = {
  current: {
    label: "Current Inventory",
    badge: "Available Now",
    disclosure: "In hand, inspected, and ready to ship.",
  },
  network: {
    label: "Collector Network",
    badge: "Available Through Our Network",
    disclosure:
      "Available through our trusted collector network. Final availability and timeline confirmed before purchase.",
  },
  pick: {
    label: "Mir’s Picks",
    badge: "Curator’s Pick",
    disclosure:
      "Curated by GCT as an interesting market opportunity or collector-worthy piece. Not currently in stock.",
  },
};

export const inventoryStatusOptions = [
  { value: "current", label: inventoryStatusContent.current.label },
  { value: "network", label: inventoryStatusContent.network.label },
  { value: "pick", label: inventoryStatusContent.pick.label },
] as const;

export type InventoryWatch = {
  slug?: string;
  brand: string;
  model: string;
  reference: string;
  inventoryStatus: InventoryStatus;
  price?: string;
  availabilityNote?: string;
  estimatedProcurementTime?: string;
  sourceType?: string;
  isOwnedByGCT?: boolean;
  canShipImmediately?: boolean;
  // Marks a piece that has sold: stays listed as social proof, badged
  // SOLD, but is excluded from search/concierge as available inventory.
  sold?: boolean;
  description: string;
  details: readonly string[];
  // Conversational selling angles (incl. honest tradeoffs) for the
  // concierge — not rendered on the listing page, which uses `details`.
  talkingPoints?: readonly string[];
  heroPhoto?: number;
  photos?: readonly {
    src: string;
    alt: string;
    width: number;
    height: number;
    className: string;
  }[];
};

export const inventoryWatches: InventoryWatch[] = [
  {
    slug: "citizen-attesa-shades-of-red-cc4077-71z",
    brand: "Citizen",
    model: "Attesa Shades of Red",
    reference: "CC4077-71Z",
    inventoryStatus: "current",
    price: "$1,970",
    availabilityNote: "In hand, inspected, and ready to ship.",
    sourceType: "GCT owned inventory",
    isOwnedByGCT: true,
    canShipImmediately: true,
    description:
      "The Citizen Attesa “Shades of Red” CC4077-71Z is a limited edition of 1,800 pieces built around a mesmerizing red sunburst dial that shifts from deep crimson to bright scarlet as the light moves across it. Underneath sits Citizen's flagship technology: light-powered Eco-Drive that never needs a battery, GPS satellite timekeeping that syncs to the correct time and zone anywhere on earth, and a Super Titanium case and bracelet that is both lighter and far harder than steel. This example is brand new in box, a full set, with card dated June 2026. At $1,970 it comes in around $200 below the lowest current Chrono24 listing.",
    details: [
      "GPS satellite-synced Eco-Drive (light-powered, no battery)",
      "Super Titanium case and bracelet",
      "Red sunburst chronograph dial",
      "Limited edition — 1,800 pieces",
      "Sapphire crystal",
      "Brand new in box, full set",
      "Card dated June 2026",
      "$1,970 — about $200 below the lowest Chrono24 listing",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/citizen-attesa-shades-of-red-cc4077-71z-1.jpg",
        alt: "Citizen Attesa Shades of Red CC4077-71Z standing upright showing the red sunburst dial",
        width: 1200,
        height: 1600,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/citizen-attesa-shades-of-red-cc4077-71z-2.jpg",
        alt: "Citizen Attesa Shades of Red CC4077-71Z in its presentation box with the red dial lit",
        width: 1200,
        height: 1600,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/citizen-attesa-shades-of-red-cc4077-71z-3.jpg",
        alt: "Citizen Attesa Shades of Red CC4077-71Z front view on the titanium bracelet",
        width: 1600,
        height: 1200,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/citizen-attesa-shades-of-red-cc4077-71z-4.jpg",
        alt: "Citizen Attesa Shades of Red CC4077-71Z profile in the ATTESA box",
        width: 1600,
        height: 1200,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/citizen-attesa-shades-of-red-cc4077-71z-5.jpg",
        alt: "Citizen Attesa Shades of Red CC4077-71Z side profile",
        width: 1200,
        height: 1600,
        className: "aspect-[3/4]",
      },
    ],
  },
  {
    slug: "bulova-shelby-racer-150th-anniversary-98b452",
    brand: "Bulova",
    model: "Shelby Racer 150th Anniversary Chronograph",
    reference: "98B452",
    inventoryStatus: "current",
    price: "$1,175",
    availabilityNote: "In hand, inspected, and ready to ship.",
    sourceType: "GCT owned inventory",
    isOwnedByGCT: true,
    canShipImmediately: true,
    description:
      "The Bulova 98B452 Shelby Racer celebrates Bulova's 150th anniversary with a tribute to Carroll Shelby and his racing legacy. Limited to 7,500 pieces, it pairs a blue-and-silver motorsport dial and gold-tone accents with a tachymeter scale, three chronograph registers, and a caseback engraved with the Shelby cobra and Carroll Shelby's signature. It ships on a blue-and-cream racing-stripe strap that nods to the classic Shelby livery. Brand new in box, a full set, with card dated June 2026. At $1,175 it comes in about $175 below retail.",
    details: [
      "Chronograph with tachymeter scale",
      "Blue-and-silver racing dial, gold-tone accents",
      "Caseback engraved with the Carroll Shelby signature",
      "Blue-and-cream racing-stripe strap",
      "Limited edition — 7,500 pieces",
      "Bulova 150th Anniversary tribute",
      "Brand new in box, full set",
      "$1,175 — about $175 below retail",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/bulova-shelby-racer-98b452-1.jpg",
        alt: "Bulova Shelby Racer 98B452 dial close-up showing the blue and silver chronograph",
        width: 1200,
        height: 1600,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/bulova-shelby-racer-98b452-2.jpg",
        alt: "Bulova Shelby Racer 98B452 full set displayed with the Shelby model car",
        width: 1200,
        height: 1600,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/bulova-shelby-racer-98b452-3.jpg",
        alt: "Bulova Shelby Racer 98B452 angled view on its cushion",
        width: 1600,
        height: 1200,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/bulova-shelby-racer-98b452-4.jpg",
        alt: "Bulova Shelby Racer 98B452 caseback engraved with the Carroll Shelby signature",
        width: 1200,
        height: 1600,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/bulova-shelby-racer-98b452-5.jpg",
        alt: "Bulova Shelby Racer 98B452 box and papers",
        width: 1200,
        height: 1600,
        className: "aspect-[3/4]",
      },
    ],
  },
  {
    slug: "bell-ross-br-03-94-blacktrack",
    brand: "Bell & Ross",
    model: "BR 03-94 Blacktrack",
    reference: "BR0394-BTR-CE/SCA",
    inventoryStatus: "current",
    price: "$3,200",
    availabilityNote: "In hand, inspected, and ready to ship. From Mir's personal collection.",
    sourceType: "GCT owned inventory",
    isOwnedByGCT: true,
    canShipImmediately: true,
    description:
      "A collaboration between Bell & Ross and Blacktrack, the custom motorcycle studio of designer Sacha Lakic — limited to 500 pieces, and this is number 131. The 42mm matte black ceramic case carries B&R's BR-CAL.301 automatic chronograph behind a smoked grey-on-black dial with red accents that echo the café racer that inspired it; the caseback is engraved with the bike itself. The bi-material strap pairs black calf leather over red rubber, so a line of red flashes at the edge whenever the watch moves on the wrist. This one comes from my personal collection — worn sparingly and kept in its box. The case and dial present essentially as new; the strap shows light wear from careful use. Complete with the original box and Jomashop paperwork. At $3,200 it sits well under what the edition commanded at launch, for a numbered piece that rarely comes up for sale.",
    details: [
      "42mm matte black ceramic case",
      "BR-CAL.301 automatic chronograph movement",
      "Limited edition no. 131 of 500",
      "Designed with Sacha Lakic of Blacktrack Motorcycles",
      "Caseback engraved with the Blacktrack café racer",
      "Black calf leather strap over red rubber, ceramic-coated buckle",
      "100m water resistance",
      "Complete with original box and Jomashop paperwork",
    ],
    talkingPoints: [
      "Limited to 500 pieces worldwide and individually numbered — this example is 131/500, engraved on the caseback alongside the Blacktrack motorcycle.",
      "Designed with Sacha Lakic, the designer behind Blacktrack's custom café racers, which is where the red-edged strap and motorsport dial accents come from.",
      "The bi-material strap is black calf leather over red rubber, so the red only flashes at the edges in motion — subtle until it isn't.",
      "Comes from Mir's personal collection with box and Jomashop paperwork, priced at $3,200.",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/bell-ross-br0394-blacktrack-1.jpg",
        alt: "Bell & Ross BR 03-94 Blacktrack on its presentation cushion inside the box",
        width: 1200,
        height: 1600,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/bell-ross-br0394-blacktrack-2.jpg",
        alt: "Bell & Ross BR 03-94 Blacktrack dial close-up showing chronograph registers and red accents",
        width: 1200,
        height: 1600,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/bell-ross-br0394-blacktrack-3.jpg",
        alt: "Bell & Ross BR 03-94 Blacktrack straight-on view of the ceramic case and dial",
        width: 1600,
        height: 1200,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/bell-ross-br0394-blacktrack-4.jpg",
        alt: "Bell & Ross BR 03-94 Blacktrack angled profile showing case depth and strap",
        width: 1600,
        height: 1200,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/bell-ross-br0394-blacktrack-5.jpg",
        alt: "Bell & Ross BR 03-94 Blacktrack caseback engraved with the Blacktrack motorcycle, numbered 131 of 500",
        width: 1200,
        height: 1600,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/bell-ross-br0394-blacktrack-6.jpg",
        alt: "Bell & Ross BR 03-94 Blacktrack full view in box with bi-material leather and red rubber strap",
        width: 1600,
        height: 1200,
        className: "aspect-[4/3]",
      },
    ],
  },
  {
    slug: "omega-de-ville-jumping-hour-4853-61",
    brand: "Omega",
    model: "De Ville Prestige Jumping Hour",
    reference: "4853.61",
    inventoryStatus: "pick",
    price: "$7,200–$8,350",
    availabilityNote: "Not in GCT's inventory. Contact Mir to discuss sourcing options and current market availability.",
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The De Ville Jumping Hour was produced for roughly a year starting in 1998, distributed primarily through the Asian market, and discontinued before most collectors in the West knew it existed. At the time of writing, two examples exist on Chrono24 globally — that is not a typo. The complication is elegant: hours advance in a single discrete jump at the top of each hour while a conventional minutes hand continues uninterrupted. The salmon dial adds warmth to what is otherwise a reserved package. Comparable jumping hour complications from Patek Philippe or A. Lange & Söhne run $50,000 and above. At $7,200–$8,350 in the current market, the value case is unusually clear. This is the kind of reference that gets harder to find every year.",
    details: [
      "32.5mm stainless steel case",
      "Omega automatic movement",
      "Jumping hour via digital aperture display",
      "Single minutes hand",
      "Salmon dial with applied hour markers",
      "Out of production — Asian market original",
      "Approximately one year production run, 1998",
      "Current market range: $7,500–$9,000",
    ],
    heroPhoto: 1,
    photos: [
      {
        src: "/collection/omega-de-ville-jumping-hour-4853-61-1.jpg",
        alt: "Omega De Ville Prestige Jumping Hour 4853.61 full watch view showing salmon dial and jumping hour aperture",
        width: 941,
        height: 2048,
        className: "aspect-[9/20]",
      },
      {
        src: "/collection/omega-de-ville-jumping-hour-4853-61-2.jpg",
        alt: "Omega De Ville Prestige Jumping Hour 4853.61 dial close-up",
        width: 960,
        height: 960,
        className: "aspect-square",
      },
      {
        src: "/collection/omega-de-ville-jumping-hour-4853-61-3.jpg",
        alt: "Omega De Ville Prestige Jumping Hour 4853.61 case and crown detail",
        width: 960,
        height: 960,
        className: "aspect-square",
      },
      {
        src: "/collection/omega-de-ville-jumping-hour-4853-61-4.jpg",
        alt: "Omega De Ville Prestige Jumping Hour 4853.61 three-quarter view",
        width: 960,
        height: 960,
        className: "aspect-square",
      },
      {
        src: "/collection/omega-de-ville-jumping-hour-4853-61-5.jpg",
        alt: "Omega De Ville Prestige Jumping Hour 4853.61 side profile",
        width: 960,
        height: 960,
        className: "aspect-square",
      },
      {
        src: "/collection/omega-de-ville-jumping-hour-4853-61-6.jpg",
        alt: "Omega De Ville Prestige Jumping Hour 4853.61 detail view",
        width: 960,
        height: 960,
        className: "aspect-square",
      },
      {
        src: "/collection/omega-de-ville-jumping-hour-4853-61-7.jpg",
        alt: "Omega De Ville Prestige Jumping Hour 4853.61 additional view",
        width: 960,
        height: 960,
        className: "aspect-square",
      },
    ],
  },
  {
    slug: "glashutte-original-panomaticinverse",
    brand: "Glashütte Original",
    model: "PanoMaticInverse",
    reference: "1-91-02-02-02-30",
    inventoryStatus: "pick",
    price: "$7,800–$11,000",
    availabilityNote: "Not in GCT's inventory. Contact Mir to discuss sourcing options and current market availability.",
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The PanoMaticInverse does something almost no other watch does: it puts the movement's most visually compelling components — the mainspring barrel and balance wheel — at twelve o'clock, visible through an aperture in the upper dial, while the hours and minutes read from an off-center sub-dial below. The result is a watch that shows you its mechanical argument rather than hiding it. Glashütte Original builds this on their in-house Calibre 91-02, with the movement decoration — three-quarter plate, Glashütte ribbing, blued screws — visible through the exhibition caseback. The asymmetric case design is distinctive without being theatrical. New and unworn examples start around $11,000; full-set pre-owned in very good condition begins around $7,800. For a manufacture complication at this level of finishing, that range is worth serious attention.",
    details: [
      "42mm stainless steel case",
      "Glashütte Original Calibre 91-02 automatic",
      "Inverse display — barrel and balance at 12 o'clock",
      "Off-center hours and minutes sub-dial",
      "Small seconds, date",
      "Exhibition caseback — three-quarter plate movement",
      "Glashütte ribbing and blued screw finishing",
      "New unworn: ~$11,000 · Pre-owned full set: from $7,800",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/glashutte-original-panomaticinverse-1-91-02-02-02-30-1.jpg",
        alt: "Glashütte Original PanoMaticInverse reference 1-91-02-02-02-30 showing inverse display and asymmetric dial",
        width: 945,
        height: 2048,
        className: "aspect-[9/20]",
      },
    ],
  },
  {
    slug: "grand-seiko-heritage-sbgh351g-rikka",
    brand: "Grand Seiko",
    model: "Heritage Collection",
    reference: "SBGH351G · Rikka",
    inventoryStatus: "current",
    price: "$5,495",
    availabilityNote: inventoryStatusContent.current.disclosure,
    sourceType: "GCT owned inventory",
    isOwnedByGCT: true,
    canShipImmediately: true,
    sold: true,
    description:
      "Rikka — standing flowers — marks the start of summer in the traditional Japanese calendar of twenty-four seasons. Grand Seiko built a dial around that moment: a deep, textured green that shifts character as light moves across it, referencing the dense plant growth of early summer without explaining itself too literally. The case is 40mm Ever-Brilliant Steel finished by hand through Zaratsu polishing — the mirror-flat surfaces that define what Grand Seiko means by craft. Inside, the Calibre 9S85 runs Hi-Beat at 36,000 vibrations per hour, rated at +5/-3 seconds per day. Brand new, unworn, full set with card dated May 2026.",
    details: [
      "40mm Ever-Brilliant Steel — Zaratsu polished",
      "Grand Seiko Calibre 9S85 automatic",
      "Hi-Beat 36,000 vph — +5/−3 sec/day accuracy",
      "55-hour power reserve",
      "Deep green Rikka textured dial",
      "Applied steel markers, gold seconds hand",
      "100m water resistance",
      "Brand new, unworn — full set, card dated May 2026",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/grand-seiko-heritage-sbgh351g-rikka-1.jpg",
        alt: "Grand Seiko Heritage SBGH351G Rikka deep green dial front view",
        width: 1246,
        height: 1662,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/grand-seiko-heritage-sbgh351g-rikka-2.jpg",
        alt: "Grand Seiko SBGH351G Rikka dial close-up showing green texture",
        width: 1029,
        height: 1372,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/grand-seiko-heritage-sbgh351g-rikka-3.jpg",
        alt: "Grand Seiko SBGH351G Rikka three-quarter case view",
        width: 1199,
        height: 1599,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/grand-seiko-heritage-sbgh351g-rikka-4.jpg",
        alt: "Grand Seiko SBGH351G Rikka side profile showing case finishing",
        width: 1536,
        height: 2048,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/grand-seiko-heritage-sbgh351g-rikka-5.jpg",
        alt: "Grand Seiko SBGH351G Rikka caseback view",
        width: 1102,
        height: 1469,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/grand-seiko-heritage-sbgh351g-rikka-6.jpg",
        alt: "Grand Seiko SBGH351G Rikka full set with box and papers",
        width: 1536,
        height: 2048,
        className: "aspect-[3/4]",
      },
    ],
  },
  {
    slug: "filippo-loreti-retro-chrono-verde",
    brand: "Filippo Loreti",
    model: "Retro Chrono Verde",
    reference: "Retro Chrono | Verde",
    inventoryStatus: "current",
    price: "$149",
    availabilityNote: inventoryStatusContent.current.disclosure,
    sourceType: "GCT owned inventory",
    isOwnedByGCT: true,
    canShipImmediately: true,
    description:
      "The Retro Chrono Verde is Filippo Loreti's most visually arresting piece — a cushion case chronograph with a deep green sunburst dial that fades from emerald at the center to near-black at the outer registers. The gold-tone case and pushers give it a vintage racing character reminiscent of 1970s competition chronographs, without the complications of sourcing the real thing. This example is brand new and unregistered. Retail is $190 direct from Filippo Loreti. We're moving it at $149 — below our cost — to make room. If you've been curious about the brand or want a conversation-starting chronograph at a price that doesn't hurt, this is the one.",
    details: [
      "42mm cushion stainless steel case, gold PVD",
      "Green sunburst dial, gradient to black outer registers",
      "Tachymeter bezel",
      "Chronograph — hours, minutes, running seconds subdials",
      "Japanese Miyota OS20 quartz movement",
      "Black leather strap",
      "50m water resistance",
      "Brand new, unregistered — below retail",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/filippo-loreti-retro-chrono-verde-1.jpeg",
        alt: "Filippo Loreti Retro Chrono Verde front view showing green sunburst dial and gold-tone case",
        width: 4032,
        height: 3024,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/filippo-loreti-retro-chrono-verde-2.jpeg",
        alt: "Filippo Loreti Retro Chrono Verde dial close-up showing chronograph subdials",
        width: 4032,
        height: 3024,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/filippo-loreti-retro-chrono-verde-3.jpeg",
        alt: "Filippo Loreti Retro Chrono Verde in presentation box",
        width: 4032,
        height: 3024,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/filippo-loreti-retro-chrono-verde-4.jpeg",
        alt: "Filippo Loreti Retro Chrono Verde three-quarter view showing case and pushers",
        width: 4032,
        height: 3024,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/filippo-loreti-retro-chrono-verde-5.jpeg",
        alt: "Filippo Loreti Retro Chrono Verde profile view on surface",
        width: 4032,
        height: 3024,
        className: "aspect-[4/3]",
      },
    ],
  },
  {
    slug: "rado-captain-cook-ceramic-skeleton-r32192152",
    brand: "Rado",
    model: "Captain Cook High-Tech Ceramic Skeleton",
    reference: "R32192152",
    inventoryStatus: "current",
    price: "$4,490",
    availabilityNote: inventoryStatusContent.current.disclosure,
    sourceType: "GCT owned inventory",
    isOwnedByGCT: true,
    canShipImmediately: true,
    sold: true,
    description:
      "The Rado Captain Cook High-Tech Ceramic Skeleton blends modern materials with aggressive industrial design. Matte black ceramic keeps the watch lightweight and stealthy, while warm rose gold-tone accents add contrast and depth. The open-worked dial and exhibition caseback show the automatic movement from both sides, giving the piece a technical character that feels equal parts motorsport instrumentation and contemporary architecture. This example is brand new and unworn — never on a wrist — with a card dated April 2026.",
    details: [
      "43mm high-tech matte black ceramic case and bracelet",
      "Rose gold-tone bezel, crown, and dial accents",
      "Skeletonized automatic movement",
      "Sapphire crystal",
      "Exhibition caseback",
      "300m water resistance",
      "Full set with box and papers",
      "Brand new, unworn — card dated April 2026",
    ],
    talkingPoints: [
      "The matte black ceramic construction gives the watch a lightweight, modern, stealthy feel.",
      "Rose gold-tone accents add warmth and contrast without making the watch feel overly flashy.",
      "The skeleton dial and exhibition caseback make the movement a major visual part of the experience.",
      "At 43mm with strong contrast, it has real wrist presence and may feel large for buyers who prefer compact watches.",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/rado-captain-cook-high-tech-ceramic-skeleton-1.jpg",
        alt: "Close-up of the Rado Captain Cook High-Tech Ceramic Skeleton with rose gold-tone bezel accents",
        width: 1536,
        height: 2048,
        className: "aspect-[4/5]",
      },
      {
        src: "/collection/rado-captain-cook-high-tech-ceramic-skeleton-2.jpg",
        alt: "Side view of the Rado Captain Cook High-Tech Ceramic Skeleton showing the ceramic case and rose gold-tone bezel",
        width: 1536,
        height: 2048,
        className: "aspect-[4/5]",
      },
      {
        src: "/collection/rado-captain-cook-high-tech-ceramic-skeleton-3.jpg",
        alt: "Crown-side profile of the Rado Captain Cook High-Tech Ceramic Skeleton",
        width: 1536,
        height: 2048,
        className: "aspect-[4/5]",
      },
      {
        src: "/collection/rado-captain-cook-high-tech-ceramic-skeleton-4.jpg",
        alt: "Rado Captain Cook High-Tech Ceramic Skeleton matte black ceramic bracelet and clasp",
        width: 1536,
        height: 2048,
        className: "aspect-[4/5]",
      },
      {
        src: "/collection/rado-captain-cook-high-tech-ceramic-skeleton-5.jpg",
        alt: "Exhibition caseback of the Rado Captain Cook High-Tech Ceramic Skeleton",
        width: 1335,
        height: 1780,
        className: "aspect-[4/5]",
      },
      {
        src: "/collection/rado-captain-cook-high-tech-ceramic-skeleton-6.jpg",
        alt: "Rado Captain Cook High-Tech Ceramic Skeleton full set with box and papers",
        width: 1536,
        height: 2048,
        className: "aspect-[4/5]",
      },
    ],
  },
  // ── Collector Network ─────────────────────────────────────────────────────
  {
    slug: "omega-de-ville-hour-vision-433-10-41-21-03-001",
    brand: "Omega",
    model: "De Ville Hour Vision",
    reference: "433.10.41.21.03.001",
    inventoryStatus: "network",
    availabilityNote: inventoryStatusContent.network.disclosure,
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Hour Vision makes the case for an exhibition dress watch without resorting to skeletonization. Sapphire crystal panels on the case sides expose the Calibre 8900 movement — bridges, rotor, and balance — while the blue dial stays clean up front. Master Chronometer rated to +0/−5 seconds per day. This example is in great condition with the newer wood presentation box, booklet, and three cards dated 2023.",
    details: [
      "41mm stainless steel case",
      "Omega Calibre 8900 automatic — Master Chronometer",
      "Blue dial with applied hour markers",
      "Exhibition sapphire crystal case sides",
      "New-style wood box, booklet, 3 cards dated 2023",
      "Great condition",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/715241298_2207887249615778_454172686537735431_n.jpg",
        alt: "Omega De Ville Hour Vision 433.10.41.21.03.001 blue dial on wrist",
        width: 2048,
        height: 2048,
        className: "aspect-square",
      },
    ],
  },
  {
    slug: "omega-seamaster-at150-38-5mm-231-10-39-21-02-002",
    brand: "Omega",
    model: "Seamaster Aqua Terra 150m",
    reference: "231.10.39.21.02.002",
    inventoryStatus: "network",
    availabilityNote: inventoryStatusContent.network.disclosure,
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The 38.5mm Aqua Terra sits at the smaller end of the AT150 range — enough water resistance to justify the Seamaster name, proportions closer to a dress watch. Calibre 8500 Co-Axial. White dial, leather presentation box, booklet, two undated cards, 16+2 links. Just came back from a full service with the watchmaker's receipt included.",
    details: [
      "38.5mm stainless steel case",
      "Omega Calibre 8500 Co-Axial automatic",
      "White dial",
      "Leather box, booklet, 2 cards undated",
      "16+2 bracelet links",
      "Recently fully serviced — watchmaker receipt included",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/716209924_3208916816163616_5917768479798070218_n.jpg",
        alt: "Omega Seamaster Aqua Terra 150m 231.10.39.21.02.002 white dial with box and papers",
        width: 1920,
        height: 2560,
        className: "aspect-[3/4]",
      },
    ],
  },
  {
    slug: "omega-seamaster-at150-41-5mm-231-10-42-21-02-001",
    brand: "Omega",
    model: "Seamaster Aqua Terra 150m",
    reference: "231.10.42.21.02.001",
    inventoryStatus: "network",
    availabilityNote: inventoryStatusContent.network.disclosure,
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The 41.5mm Aqua Terra on Calibre 8500 Co-Axial — the generation before the Master Co-Axial upgrade. White dial, old-style wood presentation box, booklet, three cards dated 2011, 15+2 links. Well-kept for a watch of this vintage.",
    details: [
      "41.5mm stainless steel case",
      "Omega Calibre 8500 Co-Axial automatic",
      "White dial",
      "Old-style wood box, booklet, 3 cards dated 2011",
      "15+2 bracelet links",
      "Great condition",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/713523149_1027686440210966_71863322211512770_n.jpg",
        alt: "Omega Seamaster Aqua Terra 150m 231.10.42.21.02.001 white dial with old-style wood box and cards",
        width: 1917,
        height: 2558,
        className: "aspect-[3/4]",
      },
    ],
  },
  {
    slug: "omega-seamaster-at150-ryder-cup-231-10-42-21-02-002",
    brand: "Omega",
    model: "Seamaster Aqua Terra 150m — Ryder Cup",
    reference: "231.10.42.21.02.002",
    inventoryStatus: "network",
    availabilityNote: "Available through our trusted collector network. Watch only — no box. Final availability and timeline confirmed before purchase.",
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Ryder Cup \"Captain's Watch\" variant of the 41.5mm Aqua Terra — the golf affiliation is noted on the dial without overwhelming it. Calibre 8500 Co-Axial, white dial. This example comes watch-only with two cards dated 2014 and 16+2 links. Great condition.",
    details: [
      "41.5mm stainless steel case",
      "Omega Calibre 8500 Co-Axial automatic",
      "Ryder Cup 'Captain's Watch' edition — white dial",
      "2 cards dated 2014, 16+2 bracelet links",
      "Watch only — no box",
      "Great condition",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/712983108_2139329206924339_1886172522778460700_n.jpg",
        alt: "Omega Seamaster Aqua Terra 150m Ryder Cup 231.10.42.21.02.002 with warranty card and service receipt",
        width: 2568,
        height: 1926,
        className: "aspect-[4/3]",
      },
    ],
  },
  {
    slug: "omega-seamaster-at150-master-231-10-42-21-02-003",
    brand: "Omega",
    model: "Seamaster Aqua Terra 150m",
    reference: "231.10.42.21.02.003",
    inventoryStatus: "network",
    availabilityNote: inventoryStatusContent.network.disclosure,
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Master Co-Axial upgrade to the 41.5mm AT150 brought METAS certification to the platform — tighter tolerances and magnetic resistance to 15,000 gauss. Calibre 8500, white dial, newer wood presentation box, full undated set. Great condition.",
    details: [
      "41.5mm stainless steel case",
      "Omega Calibre 8500 Master Co-Axial — METAS certified",
      "White dial",
      "New-style wood box, full set, undated cards",
      "Great condition",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/717025268_2271359050268896_5680912105966546585_n.jpg",
        alt: "Omega Seamaster Aqua Terra 150m 231.10.42.21.02.003 white dial with new-style wood box and full set",
        width: 1536,
        height: 2048,
        className: "aspect-[3/4]",
      },
    ],
  },
  {
    slug: "omega-seamaster-po600-217-30-42-21-01-003",
    brand: "Omega",
    model: "Seamaster Planet Ocean 600m",
    reference: "217.30.42.21.01.003",
    inventoryStatus: "network",
    availabilityNote: inventoryStatusContent.network.disclosure,
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Planet Ocean 600m with the polished orange ceramic bezel — the colorway that made this reference a modern dive watch benchmark. Master Chronometer Calibre 8912. This example is essentially new: full set with papers dated May 2026 and slider clasp. The orange ceramic variant consistently holds value more firmly than the steel-bezel equivalents.",
    details: [
      "42mm stainless steel case",
      "Omega Calibre 8912 Master Chronometer",
      "Polished orange ceramic bezel",
      "Full set dated May 2026",
      "Slider clasp",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/710365070_1797682714973148_4309187445095448717_n.jpg",
        alt: "Omega Seamaster Planet Ocean 600m 217.30.42.21.01.003 orange ceramic bezel full set in box",
        width: 1536,
        height: 2048,
        className: "aspect-[3/4]",
      },
    ],
  },
  {
    slug: "tudor-black-bay-58-burgundy-m7939a1a0ru-0003",
    brand: "Tudor",
    model: "Black Bay 58",
    reference: "M7939A1A0RU-0003 · Burgundy",
    inventoryStatus: "network",
    availabilityNote: "Available through our trusted collector network. Note: rubber strap trimmed to fit 6.9\" wrist. Extra jubilee bracelet included. Final availability and timeline confirmed before purchase.",
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Black Bay 58 in its original burgundy colorway — the reference that reestablished Tudor as a serious collector brand. 39mm, Manufacture Calibre MT5400-U (COSC and METAS certified), full set dated May 2025. The original rubber strap has been shortened to fit a 6.9-inch wrist; the watch comes with an additional AM micro-adjustment jubilee bracelet.",
    details: [
      "39mm stainless steel case",
      "Tudor Calibre MT5400-U — COSC & METAS certified",
      "Burgundy dial and bezel",
      "Full set dated May 2025",
      "Rubber strap trimmed to fit 6.9\" wrist",
      "Extra AM micro-adjustment jubilee bracelet included",
    ],
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/716897263_1467889587966605_5326831461582025772_n.jpg",
        alt: "Tudor Black Bay 58 M7939A1A0RU-0003 burgundy dial in box with full set",
        width: 1536,
        height: 2048,
        className: "aspect-[3/4]",
      },
    ],
  },
  {
    slug: "tudor-black-bay-58-gmt-coke-riveted-m7939g1a0nru-0001",
    brand: "Tudor",
    model: "Black Bay 58 GMT",
    reference: "M7939G1A0NRU-0001 · Coke — Riveted",
    inventoryStatus: "network",
    availabilityNote: inventoryStatusContent.network.disclosure,
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Black Bay 58 GMT in the coke/black bezel on the riveted steel bracelet. The riveted bracelet gives the piece a more vintage character than the jubilee — it reads closer to a 1960s tool watch. 39mm, Manufacture Calibre MT5450-U (COSC and METAS certified). Brand new in box, dated May 2026.",
    details: [
      "39mm stainless steel case",
      "Tudor Calibre MT5450-U — COSC & METAS certified",
      "Black and red 'Coke' GMT bezel",
      "Riveted steel bracelet",
      "Brand new in box — May 2026",
    ],
    heroPhoto: 0,
    photos: [],
  },
  {
    slug: "tudor-black-bay-pro-opaline-m79470-0004",
    brand: "Tudor",
    model: "Black Bay Pro",
    reference: "M79470-0004 · Opaline",
    inventoryStatus: "network",
    availabilityNote: inventoryStatusContent.network.disclosure,
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Black Bay Pro fits a GMT complication into 39mm without crowding the dial — the 24-hour GMT hand integrates cleanly into a layout that stays legible. Opaline dial, Manufacture Calibre MT5652. Brand new in box, dated April 2026.",
    details: [
      "39mm stainless steel case",
      "Tudor Calibre MT5652 automatic — GMT",
      "Opaline dial",
      "Brand new in box — April 2026",
    ],
    heroPhoto: 0,
    photos: [],
  },
  {
    slug: "tudor-black-bay-58-gmt-coke-jubilee-m7939g1a0nru-0003",
    brand: "Tudor",
    model: "Black Bay 58 GMT",
    reference: "M7939G1A0NRU-0003 · Coke — Jubilee",
    inventoryStatus: "network",
    availabilityNote: inventoryStatusContent.network.disclosure,
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Black Bay 58 GMT in the coke/black bezel configuration on the jubilee bracelet. The five-link jubilee dresses the watch up considerably compared to the riveted option — it reads more like a daily wear piece than a sport watch. 39mm, Manufacture Calibre MT5450-U (COSC and METAS certified). Brand new in box, dated April 2026.",
    details: [
      "39mm stainless steel case",
      "Tudor Calibre MT5450-U — COSC & METAS certified",
      "Black and red 'Coke' GMT bezel",
      "Jubilee bracelet",
      "Brand new in box — April 2026",
    ],
    heroPhoto: 0,
    photos: [],
  },
  {
    slug: "tudor-black-bay-54-lagoon-blue-m79000-0001",
    brand: "Tudor",
    model: "Black Bay 54",
    reference: "M79000-0001 · Lagoon Blue",
    inventoryStatus: "network",
    availabilityNote: inventoryStatusContent.network.disclosure,
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Black Bay 54 \"Lagoon Blue\" is the most visually arresting watch in Tudor's current lineup — a powder blue dial and bezel that references 1950s dive watch aesthetics without cosplaying them. At 37mm it wears smaller than the 39mm Black Bay 58, which suits the vintage brief. Manufacture Calibre MT5400. Brand new in box, dated May 2026.",
    details: [
      "37mm stainless steel case",
      "Tudor Calibre MT5400 automatic",
      "Lagoon Blue dial and bezel",
      "Brand new in box — May 2026",
    ],
    heroPhoto: 0,
    photos: [],
  },
  {
    slug: "tudor-black-bay-58-black-m79030n-0001",
    brand: "Tudor",
    model: "Black Bay 58",
    reference: "M79030N-0001 · Black",
    inventoryStatus: "network",
    availabilityNote: inventoryStatusContent.network.disclosure,
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Black Bay 58 in the all-black configuration — the most reduced expression of the reference. Black dial, black bezel insert, steel case. No color distraction from the snowflake hands and the proportions. Manufacture Calibre MT5402 (COSC certified). Brand new in box, dated April 2026.",
    details: [
      "39mm stainless steel case",
      "Tudor Calibre MT5402 — COSC certified",
      "Black dial and bezel",
      "Brand new in box — April 2026",
    ],
    heroPhoto: 0,
    photos: [],
  },
  {
    slug: "tudor-black-bay-58-blue-m79030b-0001",
    brand: "Tudor",
    model: "Black Bay 58",
    reference: "M79030B-0001 · Blue",
    inventoryStatus: "network",
    availabilityNote: inventoryStatusContent.network.disclosure,
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Black Bay 58 blue remains the closest thing to a modern reissue of the original Tudor dive watch — snowflake hands, pencil bezel pip, 39mm case that actually fits. Manufacture Calibre MT5402 (COSC certified). Brand new in box, dated May 2026.",
    details: [
      "39mm stainless steel case",
      "Tudor Calibre MT5402 — COSC certified",
      "Blue dial and bezel",
      "Brand new in box — May 2026",
    ],
    heroPhoto: 0,
    photos: [],
  },
  {
    slug: "tudor-pelagos-39-m25407n-0001",
    brand: "Tudor",
    model: "Pelagos 39",
    reference: "M25407N-0001 · Black",
    inventoryStatus: "network",
    availabilityNote: inventoryStatusContent.network.disclosure,
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Pelagos 39 brings the professional dive watch brief into a 39mm titanium case — lighter on the wrist than any steel equivalent, with the T-fit micro-adjustment clasp that makes sizing genuinely easy. It has a tool-watch authenticity the Black Bay line doesn't quite reach. Manufacture Calibre MT5400 (COSC certified). Brand new in box, dated March 2026.",
    details: [
      "39mm titanium case and bracelet",
      "Tudor Calibre MT5400 — COSC certified",
      "Black dial",
      "T-fit micro-adjustment folding clasp",
      "Brand new in box — March 2026",
    ],
    heroPhoto: 0,
    photos: [],
  },
  {
    slug: "tudor-black-bay-pro-black-m79470-0001",
    brand: "Tudor",
    model: "Black Bay Pro",
    reference: "M79470-0001 · Black",
    inventoryStatus: "network",
    availabilityNote: "Available through our trusted collector network. Note: 11 links present — fits up to approximately 7.25\" wrist. Final availability and timeline confirmed before purchase.",
    isOwnedByGCT: false,
    canShipImmediately: false,
    description:
      "The Black Bay Pro GMT in black — a blacked-out dial that reads more like a field instrument than a dress watch. The GMT complication is handled cleanly at this size; 39mm keeps it wearable. Manufacture Calibre MT5652. Full set dated August 2022, 11 links (fits up to approximately 7.25-inch wrist). Great condition.",
    details: [
      "39mm stainless steel case",
      "Tudor Calibre MT5652 automatic — GMT",
      "Black dial",
      "Full set dated August 2022",
      "11 links — fits up to approximately 7.25\" wrist",
      "Great condition",
    ],
    heroPhoto: 0,
    photos: [],
  },
];

export const currentInventoryWatches = inventoryWatches.filter(
  (watch) => watch.inventoryStatus === "current",
);

export const legacyInventoryWatches = [
  {
    brand: "Omega",
    model: "Speedmaster Moonwatch Professional",
    reference: "310.30.42.50.04.001 · Sourced & delivered",
    category: "Sourced on request",
    description:
      "White-dial Moonwatch Professional Co-Axial Master Chronometer chronograph on the steel bracelet — sourced on request for a client and delivered complete with box and cards. A recent example of the concierge sourcing service: name the reference, and we find it.",
    image: {
      src: "/collection/omega-speedmaster-moonwatch-1.jpg",
      alt: "Omega Speedmaster Moonwatch Professional white dial chronograph, sourced on request and delivered",
      width: 1022,
      height: 1500,
      className: "aspect-[2/3]",
    },
    photos: [
      {
        src: "/collection/omega-speedmaster-moonwatch-1.jpg",
        alt: "Omega Speedmaster Moonwatch Professional white dial, front view",
        width: 1022,
        height: 1500,
        className: "aspect-[2/3]",
      },
      {
        src: "/collection/omega-speedmaster-moonwatch-2.jpg",
        alt: "Omega Speedmaster Moonwatch Professional three-quarter view on the steel bracelet",
        width: 831,
        height: 1500,
        className: "aspect-[5/9]",
      },
      {
        src: "/collection/omega-speedmaster-moonwatch-3.jpg",
        alt: "Omega Speedmaster Moonwatch Professional clasp with the Omega logo",
        width: 989,
        height: 1500,
        className: "aspect-[2/3]",
      },
      {
        src: "/collection/omega-speedmaster-moonwatch-4.jpg",
        alt: "Omega Speedmaster Moonwatch Professional white dial on a display stand",
        width: 702,
        height: 1500,
        className: "aspect-[7/15]",
      },
    ],
  },
  {
    brand: "Christopher Ward",
    model: "C65 Dune Aeolian GMT Blue Dial",
    reference: "Legacy piece",
    category: "GMT",
    description:
      "A blue-dial GMT with a relaxed field-watch attitude, brushed bracelet, and enough travel-watch utility to earn a place in the archive.",
    image: {
      src: "/collection/christopher-ward-c65-dune-aeolian-gmt-blue-dial.png",
      alt: "Christopher Ward C65 Dune Aeolian GMT Blue Dial shown in three archival views",
      width: 1360,
      height: 1156,
      className: "aspect-[4/3]",
    },
  },
  {
    brand: "Maurice Lacroix",
    model: "AIKON Mercury",
    reference: "AI6088-SS002-030-1 | Full Set",
    category: "Free hand",
    description:
      "One of the most unconventional modern complications in contemporary watchmaking: a patented free-hand system where the hour and minute hands drift away from conventional timekeeping and dynamically return when the watch is moved or engaged.",
    image: {
      src: "/collection/maurice-lacroix-aikon-mercury-full-presentation.png",
      alt: "Maurice Lacroix AIKON Mercury shown with dial view, full set, and exhibition caseback",
      width: 1536,
      height: 1024,
      className: "aspect-[3/2]",
    },
  },
  {
    brand: "Omega",
    model: "Speedmaster Reduced",
    reference: "3510.80.00 | Watch, box, card",
    category: "Chronograph",
    description:
      "A blue-dial Speedmaster Reduced with the crisp tri-register layout and compact proportions that make the reference especially wearable, archived with its red Omega box and card.",
    image: {
      src: "/collection/omega-speedmaster-reduced-3510-80-00-box-card.png",
      alt: "Omega Speedmaster Reduced 3510.80.00 with blue dial, red box, and card",
      width: 1402,
      height: 1122,
      className: "aspect-[4/3]",
    },
  },
] as const;

export const collectionWatches = [
  {
    brand: "Hublot",
    model: "Classic Fusion Aerofusion Moonphase",
    reference: "517.CX.0170.LR",
    description:
      "A 45mm black ceramic Classic Fusion with a fully skeletonized dial that puts the movement architecture on display — twin date apertures at twelve, and a moonphase with pointer date at six that reads like an instrument cluster. The blackened case and black alligator-over-rubber strap keep the whole package monochrome, so the openworked dial and the blue of the moon disc do all the talking. For the stargazers.",
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/hublot-aerofusion-moonphase-1.jpg",
        alt: "Hublot Classic Fusion Aerofusion Moonphase 517.CX.0170.LR on its presentation cushion",
        width: 1600,
        height: 1200,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/hublot-aerofusion-moonphase-2.jpg",
        alt: "Hublot Aerofusion Moonphase skeleton dial close-up showing the moonphase and pointer date",
        width: 1200,
        height: 1600,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/hublot-aerofusion-moonphase-3.jpg",
        alt: "Hublot Aerofusion Moonphase angled view showing the ceramic case and alligator strap",
        width: 1600,
        height: 1200,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/hublot-aerofusion-moonphase-4.jpg",
        alt: "Hublot Aerofusion Moonphase low profile view of the case and skeleton dial",
        width: 1600,
        height: 1200,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/hublot-aerofusion-moonphase-5.jpg",
        alt: "Hublot Aerofusion Moonphase caseback with sapphire display and visible rotor",
        width: 1600,
        height: 1200,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/hublot-aerofusion-moonphase-6.jpg",
        alt: "Hublot Aerofusion Moonphase in the box on its cushion",
        width: 1200,
        height: 1600,
        className: "aspect-[3/4]",
      },
    ],
  },
  {
    brand: "M.A.D.Editions",
    model: "M.A.D. 1",
    reference: "M.A.D. 1",
    description:
      "An unconventional collector piece built around the playful side of independent watchmaking, with a visible top-mounted rotor, lateral time display, and a mechanical presence that feels more like kinetic design than a conventional dial.",
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/mad-1-1882.jpg",
        alt: "M.A.D. 1 displayed on a watch stand with the top-mounted rotor visible",
        width: 1536,
        height: 2048,
        className: "aspect-[4/5]",
      },
      {
        src: "/collection/mad-1-1883.jpg",
        alt: "M.A.D. 1 side view on a watch stand with garden background",
        width: 1536,
        height: 2048,
        className: "aspect-[4/5]",
      },
      {
        src: "/collection/mad-1-1891.jpg",
        alt: "Low side profile of the M.A.D. 1 showing the case, rotor, and strap",
        width: 1536,
        height: 2048,
        className: "aspect-[4/5]",
      },
    ],
  },
  {
    brand: "Rolex",
    model: "Datejust 36",
    reference: "126231",
    description:
      "A two-tone Datejust 36 with Everose Rolesor warmth, a fluted bezel, Jubilee bracelet, white Roman dial, and classic 36mm proportions. It sits in the sweet spot between dress-watch polish and daily-wear Rolex familiarity.",
    heroPhoto: 0,
    photos: [
      {
        src: "/images/datejust-126231/datejust-126231-desktop-hero.jpg",
        alt: "Rolex Datejust 36 reference 126231 angled on a tabletop with the Jubilee bracelet open",
        width: 1800,
        height: 1254,
        className: "aspect-[10/7]",
      },
      {
        src: "/images/datejust-126231/datejust-126231-wrist-01-v2-web.jpg",
        alt: "Rolex Datejust 36 reference 126231 on wrist three-quarter view",
        width: 1600,
        height: 1600,
        className: "aspect-square",
      },
      {
        src: "/images/datejust-126231/datejust-126231-desktop-winder.jpg",
        alt: "Rolex Datejust 36 reference 126231 shown on a watch winder",
        width: 1305,
        height: 1800,
        className: "aspect-[3/4]",
      },
    ],
  },
  {
    brand: "Ulysse Nardin",
    model: "Maxi Marine Chronometer",
    reference: "263-66",
    description:
      "The Maxi Marine Chronometer earns the nautical heritage through substance rather than costume. The COSC-certified movement, dual-register layout — power reserve at nine, running seconds with date at six — and the deep blue dial with white Roman numerals make the case for a working sea watch without borrowing from anyone else's aesthetic. The two-tone execution, polished steel with a gold bezel, adds warmth to a piece that already carries real presence. The red '1846' at six is a detail that rewards looking.",
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/ulysse-nardin-maxi-marine-chronometer-263-66-1.jpg",
        alt: "Ulysse Nardin Maxi Marine Chronometer 263-66 angled view showing blue dial and gold bezel",
        width: 2048,
        height: 1536,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/ulysse-nardin-maxi-marine-chronometer-263-66-4.jpg",
        alt: "Ulysse Nardin Maxi Marine Chronometer 263-66 overhead flat lay on grey surface",
        width: 1536,
        height: 2048,
        className: "aspect-[3/4]",
      },
      {
        src: "/collection/ulysse-nardin-maxi-marine-chronometer-263-66-5.jpg",
        alt: "Ulysse Nardin Maxi Marine Chronometer 263-66 exhibition caseback showing UN anchor rotor",
        width: 1536,
        height: 2048,
        className: "aspect-[3/4]",
      },
    ],
  },
  {
    brand: "Breitling",
    model: "Superocean Heritage '57",
    reference: "A10370161C1X1",
    description:
      "A blue-dial Superocean Heritage with polished vintage dive-watch lines, a brown leather strap, and the kind of wrist presence that feels relaxed without going quiet.",
    heroPhoto: 2,
    photos: [
      {
        src: "/collection/breitling-superocean-heritage-57-1.jpg",
        alt: "Angled close-up of a Breitling Superocean Heritage '57 on a brown leather strap",
        width: 912,
        height: 1196,
        className: "aspect-[4/5]",
      },
      {
        src: "/collection/breitling-superocean-heritage-57-2.jpg",
        alt: "Straight-on dial view of the Breitling Superocean Heritage '57 reference A10370161C1X1",
        width: 1152,
        height: 1152,
        className: "aspect-square",
      },
      {
        src: "/collection/breitling-superocean-heritage-57-3.jpg",
        alt: "Breitling Superocean Heritage '57 displayed on a watch stand",
        width: 992,
        height: 1176,
        className: "aspect-[4/5]",
      },
    ],
  },
  {
    brand: "Chopard",
    model: "Mille Miglia GT XL",
    reference: "168459-3005",
    description:
      "A motorsport-minded chronograph with a tire-tread rubber strap, layered gray dial, and red Mille Miglia accents that make the whole piece feel properly mechanical.",
    heroPhoto: 0,
    photos: [
      {
        src: "/collection/chopard-mille-miglia-gt-xl-1.jpg",
        alt: "Chopard Mille Miglia GT XL reference 168459-3005 displayed on a watch stand",
        width: 1060,
        height: 1326,
        className: "aspect-[4/5]",
      },
      {
        src: "/collection/chopard-mille-miglia-gt-xl-2.jpg",
        alt: "Low side view of the Chopard Mille Miglia GT XL on a tire-tread rubber strap",
        width: 849,
        height: 1060,
        className: "aspect-[4/5]",
      },
      {
        src: "/collection/chopard-mille-miglia-gt-xl-3.jpg",
        alt: "Close-up of the Chopard Mille Miglia GT XL chronograph dial",
        width: 849,
        height: 1060,
        className: "aspect-[4/5]",
      },
    ],
  },
  {
    brand: "TAG Heuer",
    model: "Formula 1",
    reference: "CAZ101AM.FT8054",
    description:
      "A bright yellow Formula 1 chronograph with a black tachymeter bezel, rubber strap, and the kind of high-contrast energy that makes the watch feel built for weekends.",
    heroPhoto: 1,
    photos: [
      {
        src: "/collection/tag-heuer-formula-1-caz101am-ft8054-original.jpg",
        alt: "TAG Heuer Formula 1 reference CAZ101AM.FT8054 with yellow dial and yellow rubber strap",
        width: 4032,
        height: 3024,
        className: "aspect-[4/3]",
      },
      {
        src: "/collection/tag-heuer-formula-1-caz101am-ft8054-2.jpg",
        alt: "Angled view of the TAG Heuer Formula 1 yellow chronograph on a cushion",
        width: 1084,
        height: 1354,
        className: "aspect-[4/5]",
      },
      {
        src: "/collection/tag-heuer-formula-1-caz101am-ft8054-3.jpg",
        alt: "Close crop of the TAG Heuer Formula 1 yellow chronograph dial and black tachymeter bezel",
        width: 867,
        height: 1084,
        className: "aspect-[4/5]",
      },
    ],
  },
  {
    brand: "Omega",
    model: "Constellation Megaquartz Day-Date",
    reference: "Cal. 1310 · 1976",
    description:
      "The Constellation Megaquartz holds a specific place in Omega's history that most people walk past without knowing it. The Calibre 1310 was Omega's first in-house quartz movement — a 32 kHz Megaquartz oscillator built at a time when Omega was taking the quartz transition seriously rather than defensively. The 38mm brushed case and bezel read as restrained for 1976, the silver dial with black markers stays clean, and the caseback carries the classic constellation engraving. Two pushers flank the crown on the right side: one hacks the seconds for precise setting, the other advances the date independently. Near-mint condition, sweep seconds running correctly, date function operating as it should. A collector's piece that rewards knowing what you're looking at.",
    heroPhoto: 0,
    photos: [
      {
        src: "/images/omega-constellation-quartz/omega-constellation-quartz-hero.jpg",
        alt: "Omega Constellation Megaquartz day-date from 1976 on a suede watch stand",
        width: 940,
        height: 705,
        className: "aspect-[4/3]",
      },
      {
        src: "/images/omega-constellation-quartz/omega-constellation-quartz-angle.jpg",
        alt: "Angled view of the 1976 Omega Constellation Megaquartz day-date showing the faceted case and black leather strap",
        width: 900,
        height: 1125,
        className: "aspect-[4/5]",
      },
      {
        src: "/images/omega-constellation-quartz/omega-constellation-quartz-dial-detail.jpg",
        alt: "Close dial detail of the 1976 Omega Constellation Megaquartz day-date with brushed silver finish and day-date window",
        width: 2560,
        height: 3200,
        className: "aspect-[4/5]",
      },
    ],
  },
] as const;
